(in-package :pergamum)

(defun xform/filter-if (xform test &rest sequences)
  (labels ((iterate (acc sequences)
	     (if (notany #'null sequences)
		 (let ((crop (mapcar #'car sequences))
		       (rest (mapcar #'cdr sequences)))
		   (iterate (if (apply test crop)
				(cons (apply xform crop) acc)
				acc)
			    rest))
		 acc)))
    (nreverse (iterate nil sequences))))

(defun maybe-capture-subform (condition form accessor)
  `(or (and ,condition (,accessor ,form)) (gensym)))

(defmacro with-optional-subform-captures ((&rest specs) &body body)
  `(let ,(iter (for (vars accessors condition form) in specs)
               (appending (mapcar (lambda (var accessor)
                                    (list var (maybe-capture-subform condition form accessor)))
                                  vars accessors)))
     ,@body))
